name: Update Module Documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      changelog:
        description: 'Release changelog'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    name: Update Module Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2"

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          branch: "docs/update-for-${{ inputs.version }}"
          sha: ${{ github.sha }}

      - name: Checkout documentation branch
        uses: actions/checkout@v4
        with:
          ref: "docs/update-for-${{ inputs.version }}"

      - name: Generate documentation
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: components
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: "github-actions[bot]"
          git-push-user-email: "github-actions[bot]@users.noreply.github.com"
          git-commit-message: "docs: Update module documentation for ${{ inputs.version }} [skip ci]"
          git-push-token: ${{ secrets.GH_PAT }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: "docs/update-for-${{ inputs.version }}"
          base: main
          delete-branch: true
          title: "docs: Update module documentation for ${{ inputs.version }}"
          body: |
            ## Automated Documentation Update

            This PR updates the module documentation for release ${{ inputs.version }}.

            ### Changelog
            ${{ inputs.changelog }}

            *This is an automated PR created by the documentation workflow.*
          labels: documentation,automated

      - name: Auto approve PR
        if: steps.create-pr.outputs.pull-request-number
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_PAT }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
